apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore
  labels:
    app: datastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datastore
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
        - name: datastore
          image: larolman/datastore:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: datastore
spec:
  selector:
    app: datastore
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8034
      targetPort: 8000