apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: go-job
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: go-job
              image: larolman/go-job:latest
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: commom-secret
              command: ["./job.bin"]
          restartPolicy: OnFailure