// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	protobuf "github.com/vsantosalmeida/go-grpc-server/protobuf"
)

// PersonReceiverClient is an autogenerated mock type for the PersonReceiverClient type
type PersonReceiverClient struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: ctx, in, opts
func (_m *PersonReceiverClient) CreateEvent(ctx context.Context, in *protobuf.Person, opts ...grpc.CallOption) (*protobuf.Reply, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *protobuf.Reply
	if rf, ok := ret.Get(0).(func(context.Context, *protobuf.Person, ...grpc.CallOption) *protobuf.Reply); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protobuf.Reply)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *protobuf.Person, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
